# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        # MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(518, 486)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 231, 451))
        self.label.setStyleSheet("border-image: url(:/hoa/2.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 60, 171, 111))
        font = QtGui.QFont()
        font.setFamily("Bump Pad")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(270, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: none;\n"
"border-bottom: 3px solid rgba(170, 85, 255,255);\n"
"background-color: qradialgradient( stop:1 rgba(255, 255, 255, 0));")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 230, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border: none;\n"
"border-bottom: 3px solid rgba(170, 85, 255,255);\n"
"background-color: qradialgradient( stop:1 rgba(255, 255, 255, 0));")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.Button_lo = QtWidgets.QPushButton(self.centralwidget)
        self.Button_lo.setGeometry(QtCore.QRect(310, 330, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_lo.setFont(font)
        self.Button_lo.setStyleSheet("QPushButton#Button_lo{\n"
"    background-color: rgb(0, 170, 255);\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-right-radius: 10px; \n"
"}\n"
"QPushButton#Button_lo:hover{\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton#Button_lo:pressed{\n"
"padding-left: 2px;\n"
"padding-top: 2px;\n"
"background-color: rgb(85, 255, 0);\n"
"}")
        self.Button_lo.setObjectName("Button_lo")
        self.Button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.Button_stop.setGeometry(QtCore.QRect(450, 40, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_stop.setFont(font)
        self.Button_stop.setObjectName("Button_stop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Login"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "User Name"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Button_lo.setText(_translate("MainWindow", "Login"))
        self.Button_stop.setText(_translate("MainWindow", "x"))
import hoa_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
